# Welcome to Jekyll!
#

# Site settings
title: TAG Laboratory
description: |
  Text Analysis Group at the University of Sussex
owner: TAG Lab
first_published: 2016 # if migrating another site, the year of your first publish
email: D.J.Weir@sussex.ac.uk
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://taglaboratory.org" # the base hostname & protocol for your site
social:
  # twitter: https://twitter.com/<username>
  github: https://github.com/MLCL
  # linkedin-square: https://linkedin.com/in/<username>
  # facebook-official: https://facebook.com/<username>
  # google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

team:
  - name: Prof David Weir
    picture: /images/team/davidw-small.jpg
    interests: David co-directs the Laboratory. His research interests include mildly context-sensitive grammar formalisms, syntactic parsing and lexical semantics.
  - name: Dr Jeremy Reffin
    picture: /images/team/jeremy-small.jpeg
  - name: Simon Wibberley
    picture: /images/team/simon-small.png
  - name: Andy Robertson
    picture: /images/team/andy-small.png
  - name: Dr Miroslav Batchkarov
  - name: Jack Pay
    picture: /images/team/jack-small.jpg
  - name: Matti Lyra
  - name: Joe Taylor
    picture: /images/team/joe-small.jpg
  - name: Justin Crow
    picture: /images/team/justin-small.jpg
  - name: Thomas Kober
    picture: /images/team/thomask-small.jpg
  - name: Roland Davis
    picture: /images/team/roland-small.jpg
  - name: David Spence
  - name: Julie Weeds
  - name: Chris Inskip
  - name: Tom Ball

# Build settings
markdown: kramdown
#sass:
#  style: compressed
